ALTER TABLE projects ADD COLUMN IF NOT EXISTS start_date TIMESTAMPTZ;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS end_date TIMESTAMPTZ;
ALTER TABLE experience ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'work';
